### ISSUE TITLE
Не сохраняются изменения в документе

### ISSUE THREAD

**Issue by Selgis** [nemoware/gpn-analyse-ui#130]
В некоторых документах не сохраняются изменения после ручной разметки.
Возможно, в этих документах отсутствует одно из значений знак-значение-валюта.
Пример: http://gpn-audit.nemosoft.ru/#/audit/view/5ec2b8da665f7603e03b1262

**Comment by compartia** [comment]
```
(node:18682) UnhandledPromiseRejectionWarning: TypeError: ((warning.code === "value_section_not_found") && user.sign-value-currency) is not a function
    at exports.updateDocument (/Users/artem/work/nemo/goil/gpn-ui/projects/server/controller/document-controller.js:165:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:18682) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
```

**Comment by compartia** [comment]
@eliseysinkevich 
https://github.com/nemoware/gpn-analyse-ui/blob/82893cb72bfe7e3f4eaf2066660792cdde8c23ba/projects/server/controller/document-controller.js#L169
-- this line looks suspicious
