### ISSUE TITLE
Вкладка "Уставы"

### ISSUE THREAD

**Issue by SergeyShalaevsky** [nemoware/gpn-analyse-ui#141]
создать вкладку с уставами
Таблица уставов должна состоять из следующих столбцов: Наименование ДО, дата начала действия, дата окончания действия, дата последнего изменения, пользователь внесший последние изменения.
Так же нужна кнопка "Загрузить устав" и "сделать устав неактивным".

**Comment by compartia** [comment]
имею err при заходе в раздел Суставы
```
TypeError: current.fromDate.getTime is not a function
    at Object.keys.charters.reduce (/Users/artem/work/nemo/goil/gpn-ui/projects/server/controller/document-controller.js:539:33)
    at Array.reduce (<anonymous>)
    at setToDate (/Users/artem/work/nemo/goil/gpn-ui/projects/server/controller/document-controller.js:538:14)
    at exports.getChartersForTable (/Users/artem/work/nemo/goil/gpn-ui/projects/server/controller/document-controller.js:690:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
